### PR TITLE
Have ServiceParameters return animated values

### PR DESCRIPTION
**Pull request by metellius**
@ddennedy Is something like this what you were thinking about?
This commit compiles but I have no idea how to test it.

### CODE REVIEW

**Comment by ddennedy** [comment]
Here is how to test it
```
melt noise: out=100 -attach webvfx: resource=$HOME/shotcut/src/shotcut/src/qml/filters/webvfx_circular_frame/filter-demo.html radius="0=0; 1:0=1"
```
You can also use Shotcut, add the circular frame filter to a clip, save the project, edit the XML in a text editor, locate the filter's radius property, and paste that value: 0=0; 1:0=1. Then, you can melt the.xml or load the xml in Shotcut.

**Comment by ddennedy** [comment]
You need to modify webvfx_filter.cpp:filterGetImage() to use mlt_filter_get_length2().

**Comment by metellius** [comment]
> Here is how to test it
> 
> melt noise: out=100 -attach webvfx: resource=$HOME/shotcut/src/shotcut/src/qml/filters/webvfx_circular_frame/filter-demo.html radius="0=0; 1:0=1"

Cool, that will come in handy for other things as well.

**Comment by metellius** [comment]
I just noticed: After this commit, shotcut will enter a deadlock if I use getStringParameter from html, and then open the filter ui. Here's the backtrace:

```
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f176a69956a in _L_lock_913 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f176a699390 in __GI___pthread_mutex_lock (mutex=0x2be2cb8) at ../nptl/pthread_mutex_lock.c:79
#3  0x00007f176d905413 in mlt_property_get_string_l (self=self@entry=0x2be2c70, locale=locale@entry=0x2be3120) at mlt_property.c:706
#4  0x00007f176d905d53 in mlt_property_anim_get_string (self=0x2be2c70, fps=29.969999999999999, locale=0x2be3120, position=0, length=266) at mlt_property.c:1323
#5  0x00007f174c07b5d2 in MLTWebVfx::ServiceParameters::getStringParameter(QString const&) () from /home/harald/shotcut/Shotcut/Shotcut.app/lib/mlt/libmltwebvfx.so
#6  0x00007f17473ce0c3 in WebVfx::ContentContext::getStringParameter(QString const&) () from /home/harald/shotcut/Shotcut/Shotcut.app/lib/libwebvfx.so.1
#7  0x00007f17473d4321 in ?? () from /home/harald/shotcut/Shotcut/Shotcut.app/lib/libwebvfx.so.1
#8  0x00007f17473d464b in WebVfx::ContentContext::qt_metacall(QMetaObject::Call, int, void**) () from /home/harald/shotcut/Shotcut/Shotcut.app/lib/libwebvfx.so.1
#9  0x00007f176786764e in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5WebKit.so.5
#10 0x00007f176885fe29 in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5WebKit.so.5
#11 0x00007f1768a332da in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5WebKit.so.5
#12 0x00007f1768a3eca6 in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5WebKit.so.5
#13 0x00007f1768a45ef5 in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5WebKit.so.5
#14 0x00007f17177947d0 in ?? ()
```

**Comment by metellius** [comment]
Is it even correct to use mlt_properties_anim_get for string parameters?

**Comment by ddennedy** [comment]
Yes, strings can change over time - just not interpolated.

**Comment by ddennedy** [comment]
How are you reproducing the deadlock? I tried using the 3D Text filter in Shotcut, but it worked for me. I tried entering an animated value too. Nonetheless, I see the nested calls within mlt_property.c that cause this deadlock. I am reworking the locking for mlt_property anim functions, but wish I could more easily reproduce. I will have to see if I can make threading-related tests using QtTest, which is what MLT is using for its unit tests.
I pushed what should be a fix for this to MLT; please test it.

**Comment by metellius** [comment]
I forgot that this happened while experimenting with having the webvfx setting a filter property (in my case, the property 'text') while reading the same string in the html. Annoyingly enough, I can not reproduce it anymore, and I lost the undo history after closing my editor. I can see that 3d text does the exact some thing, so there must be something else as well affecting this (either way, I am certain I only had a diff in webvfx's ui.qml and the webvfx html I was testing).
I will delay pulling in your webvfx commit until I hopefully see the deadlock again later, then I will see if it fixes it.

**Comment by metellius** [comment]
The bug resurfaced again today - resizing the clip with the ui open turned out to be a good way to reproduce it. Pulled and recompiled libmlt, and the problem was gone. Thanks!

**Pull request merged**
